### PR TITLE
Add SonarQube configuration file

### PR DESCRIPTION
**Pull request by wynro**
^Title

### CODE REVIEW

**Review by iAbadia — COMMENTED** [review]
This seems like a good practice, can't provide valuable opinion though. @nebur395, it's your call.

**Comment by nebur395** [comment]
This is definitely a good practice. However I was wondering if it's necessary for a project as small as this.

**Review by nebur395 — COMMENTED** [review]
This is definitely a good practice. However I was wondering if it's necessary for a project as small as this.

In addition, if accepted, I think that we should establish a common basic rules to the SonarQube scanners.

**Review by Nicu1309 — APPROVED** [review]
It's OK for me. It seems kinda overkill for this project's complexity but go ahead.

**Pull request merged**
